version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
  build:
    commands:
      - cp -R ./Frontend ./Frontend-copy
  post_build:
    commands:
      - aws s3 cp Frontend-copy s3://cs6998-a2-frontend --recursive

artifacts:
  files:
    - Frontend-copy/**